name: Playwright Tests with Allure Report


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'  # Убедитесь, что версия Node.js соответствует вашей.

    - name: Install dependencies
      run: npm install

    - name: Install allure command line
      run: npm install -g allure-commandline --save-dev

    - name: Install allure-playwright
      run: npm install --save-dev @playwright/test allure-playwright
    
    - name: Install Playwright with dependencies
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npm run test

    - name: Save Allure results
      run: mkdir -p allure-results

    - name: Generate Allure report
      run: npx allure generate allure-results --clean -o allure-report

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
    
