name: Playwright Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'  # Убедитесь, что версия Node.js соответствует вашей.

    - name: Install dependencies
      run: npm install

    - name: Install allure command line
      run: npm install -g allure-commandline --save-dev

    - name: Install allure-playwright
      run: npm install --save-dev @playwright/test allure-playwright
    
    - name: Install Playwright with dependencies
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run:
        npm run test  # Запустите ваши тесты

    - name: Save Allure results
      run: mkdir -p allure-results

    - name: Generate Allure report
      run: npx allure generate allure-results --clean -o allure-report

    - name: Push Allure report to GitHub Pages branch
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Add Allure report'
        add: 'allure-report/*'

    - name: Deploy Allure report to GitHub Pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        mv allure-report/* .
        git add .
        git commit -m "Deploy Allure report"
        git push --force --set-upstream origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-gh-pages:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup GitHub Pages branch
      run: |
        git fetch origin
        git checkout gh-pages || git checkout --orphan gh-pages
        git reset --hard
        git clean -f -d

    - name: Publish Allure report to GitHub Pages
      run: |
        mv allure-report/* .
        git add .
        git commit -m "Deploy Allure Report"
        git push origin gh-pages
